baseURL: "https://whoislewys.com"
languageCode: "en-us"
title: "whoislewys"

theme: "hugo-PaperMod"
defaultTheme: dark

params:
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  profileMode:
      enabled: true
  socialIcons: # optional
      - name: "GitHub"
        url: "https://github.com/whoislewys"
menu:
  main:
    - identifier: blog
      name: blog
      url: /blog/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: work
      name: work
      url: /work/
      weight: 30
    - identifier: about
      name: about
      url: /about/
      weight: 40
